createcost: 100
renewcost: 10
movecost: 20
renamecost: 20
transfercost: 20
check-delay-ticks: 200
lookup-offline-players: true
include-essentials-warps-in-list: false

use-bstats: true

commands-on-warp-expire: []

confirm:
  create: false
  move: false
  renew: false

addons:
  save-expired-warp-locations: false
  warp-expiry-notifier:
    enabled: true
    only-owner: false
    days-for-notification: 1
  warp-limiter:
    enabled: false
    limits:      # iwarp.limits.default -> default number of warps
      default: 1 # iwarp.limits.vip -> VIP number of warps
      VIP: 3     # iwarp.limits.override -> no limit

    
messages:
  warp-already-exists: "&cWarp already exists: &6{name}"
  sender-must-be-player: "&cSender must be a player!"
  not-enough-money: "&cYou do not have enough money: &4{amount}"
  created-warp: "&7You've successfully created the warp &6{name}&7 for &8{days}&7 days days for &6{amount}&7."
  not-your-warp: "&cThis warp does not belong to you: &7{name}"
  renewed-warp: "&7You've successfully renewed the warp &6{name}&7 for another &8{days}&7 days for $&8{amount}&7 (&6{total}&7 days left in total)"
  name-not-int: "&cWarp names cannot be integers!"
  issue-while-creating-warp: "&cThere was an unexpected issue while creating warp: &4{name}"
  inssufficient-permissions: "&cYou do not have permission to use this command!"
  moved-warp: "&7You've successfully moved the warp &6{name}&7 to your current location for &8{amount}"
  issue-while-moving-warp: "&cThere was an unexpected issue while creating warp: &4{name}"
  renamed-warp: "&7You've successfully renamed the warp &8{old}&7 to &6{new}&7 for &8{amount}"
  issue-with-renaming-warp: "&cThere was an unexpected issue while renaming warp &4{old}&c to &c{new}"
  player-not-found: "&cUnable to find online player: &4{player}"
  transferred-warp: "&7Successfully transferred the warp &6{name}&7 to &8{player}&7 for &6{amount}"
  issue-with-transferring-warp: "&cUnexpected issue while transferred the warp &6{name}&7 to &8{player}"
  list-warps: "&6{player}&7 has the following warps: &8{warps}"
  warp-not-found: "&cWarp not found: &c{name}"
  warp-info: "&7The warp &6{name}&7 is owned by &8{player}&7 and will expire in &6{time}"
  confirm-create: "&7Type 'confirm' to confirm the location for warp &7{name}&7. The cost is &8{amount}&7."
  confirm-move: "&7Type 'confirm' to confirm the new location for warp &6{name}&7. The cost is &8{amount}&7."
  confirm-renew: "&7Type 'confirm' to confirm the renewal for warp &6{name}&7 for &8{days}&7 days. The cost is &8{amount}&7."
  reloaded: "&cSuccessfully loaded config and iwarps!"
  no-previous-locations: "&7No previous locations for warp &6{name}"
  previous-locations: "&7Previous locations for warp &6{name}&7: &8{locs}"
  warp-expiring: "&7The warp &7{warp}&7 will expire in &8{time}&7!"
  changed-warp-expire-date: "&7Changed the warp &6{warp}&7 to expire &8{time}&7 from now."
  have-max-warps: "&7You have &6{cur}&7 out of &8{max}&7 allowed warps"
