name: ${project.name}
version: ${project.version}
author: Ford
main: ${project.groupId}.${project.artifactId}.IWarpPlugin
api-version: 1.13
depend: [Essentials, Vault]

commands:
  iwarp:
    description: The iwarp command
    usage: "/<command> create <warpname> <days>\n/<command> renew <warpname> <days>\n/<command> move <warpname>\n/<command> rename <oldname> <newname>\n/<command> transfer <warpname> <newowner>\n/<command> list <playername>\n/<command> info <warpname\n/<command> help"
    permission: iwarp.command
  iwarpaddons:
    description: Addon commands
    usage: "/<command> [tab]"
    permission: iwarp.addons
    aliases: [iwa, iwarpa]
    
permissions:
  iwarp.command:
    description: Gives access to the main command
    default: true
  iwarp.command.create:
    description: Allow creating warps
    default: true
  iwarp.command.renew:
    description: Allow renewing warps
    default: true
  iwarp.command.move:
    description: Allow creating warps
    default: true
  iwarp.command.rename:
    description: Allow renaming warps
    default: true
  iwarp.command.adminrename:
    description: Allow renaming a warp free of charge
    default: op
  iwarp.command.transfer:
    description: Allow transferring warps
    default: true
  iwarp.command.list:
    description: Allow seeing the list of warps warps
    default: true
  iwarp.command.info:
    description: Allow seeing warp info (owner and expiry time)
    default: true
  iwarp.command.reload:
    description: Allow seeing reloading the plugin configs
    default: op
  iwarp.command.changeexpiration:
    description: Allow changing expiration of others warps
    default: op
  iwarp.addons:
    description: Allow using the addons command
    default: op
  iwarp.limits.default:
    description: Allow the default number of warps for this player (if addon enabled)
    default: true
  iwarp.limits.override:
    description: Allow any number of warps for this player (if addon enabled)
    default: op
