name: ${project.name}
version: ${project.version}
author: Ford
main: ${project.groupId}.${project.artifactId}.IWarpPlugin
api-version: 1.13
depends: [Essentials, Vault]

commands:
  iwarp:
    description: The iwarp command
    usage: "/<command> create <warpname> <days>\n/<command> renew <warpname> <days>\n/<command> move <warpname>\n/<command> rename <oldname> <newname>\n/<command> transfer <warpname> <newowner>\n/<command> list <playername>\n/<command> info <warpname\n/<command> help"
    permission: iwarp.command
    
permissions:
  iwarp.command:
    description: Gives access to the main command
    default: true
  iwarp.use:
    description: Allow creating and moving warps
    default: true
